import RequestProject.ColourCounting
import RequestProject.EntropyLaw
import RequestProject.BlockTranspose
import RequestProject.CountSectors

/-!
# Exact source-sector weights of the rectangular core

The monomial rectangle changes phases and permutes basis labels, but it does
not change entry magnitudes.  This file uses that fact to count, directly from
`X_t = W_tᴴ S_t W_t`, the sectors obtained by pulling the source colour
counts back through `W_t`.  For `t=n+1`, the marked right source site is always
`B`; the other `n` right sites contribute `j` further `B` labels, while the
left source packet contributes `l` labels of colour `A`.

The resulting normalized weight is exactly

`C(n,j) C(n+1,l) / 2^(2n+1)`,

which is Eq. (5.17), with `j=k-1`.  Identifying these pulled-back sectors with
the literal output-packet count blocks additionally uses the block-transpose
colour theorem for the crossing schedule.
-/

namespace SqrtOpEnt

open Matrix
open scoped BigOperators

variable (F : Type*) [Field F] [Fintype F] [DecidableEq F]

/-- Positive natural `n+1`, used to keep the source site total. -/
def succPNat (n : ℕ) : ℕ+ := ⟨n + 1, Nat.zero_lt_succ n⟩

/-- Source-support parameters: the common left packet and the unmarked tail
of the right packet. -/
abbrev SourceParameters (n : ℕ) := PacketBasis F (n + 1) × PacketBasis F n

/-- The unique source ket/bra pair generated by `(left, rightTail)`. -/
def sourcePairOfParameters (n : ℕ) (p : SourceParameters F n) :
    RectBasis F (n + 1) × RectBasis F (n + 1) :=
  ((p.1, Fin.cons (Sum.inr 1) p.2),
    (p.1, Fin.cons (Sum.inr 0) p.2))

omit [Fintype F] in
theorem sourcePairOfParameters_mem_support (n : ℕ) (p : SourceParameters F n) :
    rectangularSource F (succPNat n) (sourcePairOfParameters F n p).1
      (sourcePairOfParameters F n p).2 ≠ 0 := by
  rw [rectangularSource_ne_zero_iff]
  refine ⟨rfl, ?_, by simp [sourcePairOfParameters], by simp [sourcePairOfParameters]⟩
  intro k hk
  cases k using Fin.cases with
  | zero => exact (hk rfl).elim
  | succ i => simp [sourcePairOfParameters]

/-- Every nonzero source entry has unique parameters `(left,rightTail)`. -/
def sourceSupportEquiv (n : ℕ) :
    SourceParameters F n ≃
      {p : RectBasis F (n + 1) × RectBasis F (n + 1) //
        rectangularSource F (succPNat n) p.1 p.2 ≠ 0} where
  toFun p := ⟨sourcePairOfParameters F n p,
    sourcePairOfParameters_mem_support F n p⟩
  invFun p := (p.1.1.1, fun i => p.1.1.2 i.succ)
  left_inv p := by
    apply Prod.ext
    · rfl
    · funext i
      simp [sourcePairOfParameters]
  right_inv p := by
    rcases p with ⟨⟨u, v⟩, hp⟩
    have hs := (rectangularSource_ne_zero_iff F (succPNat n) u v).mp hp
    apply Subtype.ext
    apply Prod.ext
    · apply Prod.ext
      · rfl
      · funext i
        cases i using Fin.cases with
        | zero => simpa [sourcePairOfParameters] using hs.2.2.1.symm
        | succ j => simp [sourcePairOfParameters]
    · apply Prod.ext
      · change u.1 = v.1
        exact hs.1
      · funext i
        cases i using Fin.cases with
        | zero => simpa [sourcePairOfParameters] using hs.2.2.2.symm
        | succ j =>
          simp only [sourcePairOfParameters, Fin.cons_succ]
          exact hs.2.1 j.succ (by simp)

/-- Source entries with exactly `j` additional right `B` sites and `l` left
`A` sites are parameterized independently by two fixed-count packets. -/
def sourceSectorSupportEquiv (n j l : ℕ) :
    {p : RectBasis F (n + 1) × RectBasis F (n + 1) //
      rectangularSource F (succPNat n) p.1 p.2 ≠ 0 ∧
      packetBCount F (fun i => p.1.2 i.succ) = j ∧
      packetACount F p.1.1 = l} ≃
      {a : PacketBasis F (n + 1) // packetACount F a = l} ×
      {z : PacketBasis F n // packetBCount F z = j} where
  toFun p :=
    (⟨p.1.1.1, p.2.2.2⟩,
      ⟨fun i => p.1.1.2 i.succ, p.2.2.1⟩)
  invFun p :=
    ⟨sourcePairOfParameters F n (p.1.1, p.2.1),
      sourcePairOfParameters_mem_support F n _ , p.2.2, p.1.2⟩
  left_inv p := by
    apply Subtype.ext
    have he := (sourceSupportEquiv F n).apply_symm_apply
      ⟨p.1, p.2.1⟩
    change sourcePairOfParameters F n
      (p.1.1.1, fun i => p.1.1.2 i.succ) = p.1
    exact congrArg Subtype.val he
  right_inv p := by
    rcases p with ⟨⟨a, ha⟩, ⟨z, hz⟩⟩
    apply Prod.ext <;> apply Subtype.ext
    · rfl
    · funext i
      simp [sourcePairOfParameters]

/-- Exact cardinality of a source colour-count sector. -/
theorem card_sourceSectorSupport (n j l : ℕ) :
    Fintype.card {p : RectBasis F (n + 1) × RectBasis F (n + 1) //
      rectangularSource F (succPNat n) p.1 p.2 ≠ 0 ∧
      packetBCount F (fun i => p.1.2 i.succ) = j ∧
      packetACount F p.1.1 = l} =
      ((n + 1).choose l * (Fintype.card F) ^ (n + 1)) *
        (n.choose j * (Fintype.card F) ^ n) := by
  rw [Fintype.card_congr (sourceSectorSupportEquiv F n j l),
    Fintype.card_prod, card_packetACount_eq, card_packetBCount_eq]

/-! ## Pulling the counted sectors back to the coefficient matrix of `X_t` -/

/-- The elementary regrouping between a pair of coefficient-matrix indices
and the output/input indices of the operator. -/
def coeffOperatorPairEquiv (t : ℕ) :
    ((PacketBasis F t × PacketBasis F t) ×
      (PacketBasis F t × PacketBasis F t)) ≃
      RectBasis F t × RectBasis F t where
  toFun z := ((z.1.1, z.2.1), (z.1.2, z.2.2))
  invFun z := ((z.1.1, z.2.1), (z.1.2, z.2.2))
  left_inv z := by rcases z with ⟨⟨a, b⟩, ⟨c, d⟩⟩; rfl
  right_inv z := by rcases z with ⟨⟨a, b⟩, ⟨c, d⟩⟩; rfl

/-- Convert coefficient indices of `X_(n+1)` into the corresponding source
ket/bra indices by applying the rectangle support permutation. -/
def coreSourcePairEquiv (n : ℕ) :
    ((PacketBasis F (n + 1) × PacketBasis F (n + 1)) ×
      (PacketBasis F (n + 1) × PacketBasis F (n + 1))) ≃
      RectBasis F (n + 1) × RectBasis F (n + 1) :=
  (coeffOperatorPairEquiv F (n + 1)).trans
    (Equiv.prodCongr (rectangularCircuitPerm F (n + 1))
      (rectangularCircuitPerm F (n + 1)))

/-- A pair of row/column indices of the operator-Schmidt coefficient matrix. -/
abbrev CoeffIndexPair (n : ℕ) :=
  (PacketBasis F (n + 1) × PacketBasis F (n + 1)) ×
    (PacketBasis F (n + 1) × PacketBasis F (n + 1))

/-- A source ket/bra index pair. -/
abbrev SourceIndexPair (n : ℕ) :=
  RectBasis F (n + 1) × RectBasis F (n + 1)

/-- Predicate defining one source count sector. -/
def SourceSectorPredicate (n j l : ℕ) (p : SourceIndexPair F n) : Prop :=
  rectangularSource F (succPNat n) p.1 p.2 ≠ 0 ∧
    packetBCount F (fun i => p.1.2 i.succ) = j ∧
    packetACount F p.1.1 = l

noncomputable instance instDecidableSourceSectorPredicate
    (n j l : ℕ) (p : SourceIndexPair F n) :
    Decidable (SourceSectorPredicate F n j l p) := Classical.propDecidable _

/-- Cardinality theorem restated through the named sector predicate. -/
theorem card_sourceSectorPredicate (n j l : ℕ) :
    Fintype.card {p : SourceIndexPair F n // SourceSectorPredicate F n j l p} =
      ((n + 1).choose l * (Fintype.card F) ^ (n + 1)) *
        (n.choose j * (Fintype.card F) ^ n) := by
  let e : {p : SourceIndexPair F n // SourceSectorPredicate F n j l p} ≃
      {p : RectBasis F (n + 1) × RectBasis F (n + 1) //
        rectangularSource F (succPNat n) p.1 p.2 ≠ 0 ∧
        packetBCount F (fun i => p.1.2 i.succ) = j ∧
        packetACount F p.1.1 = l} :=
    Equiv.subtypeEquivRight (fun _ => by rfl)
  calc
    Fintype.card {p : SourceIndexPair F n // SourceSectorPredicate F n j l p} =
        Fintype.card {p : RectBasis F (n + 1) × RectBasis F (n + 1) //
          rectangularSource F (succPNat n) p.1 p.2 ≠ 0 ∧
          packetBCount F (fun i => p.1.2 i.succ) = j ∧
          packetACount F p.1.1 = l} := Fintype.card_congr e
    _ = _ := card_sourceSectorSupport F n j l

omit [Fintype F] in
/-- A nonzero source entry is literally the scalar `1`. -/
theorem rectangularSource_eq_one_of_ne_zero (n : ℕ)
    (u v : RectBasis F (n + 1))
    (h : rectangularSource F (succPNat n) u v ≠ 0) :
    rectangularSource F (succPNat n) u v = 1 := by
  unfold rectangularSource packetSiteOperator sourceMatrixUnit at h ⊢
  split_ifs at h ⊢ <;> simp_all

omit [Fintype F] in
/-- Squared magnitudes of source entries are support indicators. -/
theorem normSq_rectangularSource (n : ℕ) (u v : RectBasis F (n + 1)) :
    ‖rectangularSource F (succPNat n) u v‖ ^ 2 =
      if rectangularSource F (succPNat n) u v ≠ 0 then 1 else 0 := by
  by_cases h : rectangularSource F (succPNat n) u v ≠ 0
  · rw [if_pos h, rectangularSource_eq_one_of_ne_zero F n u v h]
    simp
  · rw [if_neg h]
    push_neg at h
    rw [h]
    simp

/-- Entry magnitudes of the coefficient matrix of `X_t`, expressed at the
corresponding source coordinates. -/
theorem norm_rectCoeff_rectangularCore_apply (psi : AddChar F ℂ) (n : ℕ)
    (x y : PacketBasis F (n + 1) × PacketBasis F (n + 1)) :
    ‖rectCoeff F (rectangularCore F psi (succPNat n)) x y‖ =
      ‖rectangularSource F (succPNat n) (coreSourcePairEquiv F n (x, y)).1
        (coreSourcePairEquiv F n (x, y)).2‖ := by
  simpa [coreSourcePairEquiv, coeffOperatorPairEquiv] using
    norm_rectangularCore_apply F psi (succPNat n) (x.1, y.1) (x.2, y.2)

/-- The concrete coefficient-matrix block selected by source counts pulled
back through the rectangle. -/
noncomputable def pulledSourceSectorBlock (psi : AddChar F ℂ)
    (n j l : ℕ) :
    Matrix (PacketBasis F (n + 1) × PacketBasis F (n + 1))
      (PacketBasis F (n + 1) × PacketBasis F (n + 1)) ℂ :=
  fun x y =>
    let p := coreSourcePairEquiv F n (x, y)
    if packetBCount F (fun i => p.1.2 i.succ) = j ∧
        packetACount F p.1.1 = l then
      rectCoeff F (rectangularCore F psi (succPNat n)) x y
    else 0

/-- The pulled-back source sectors are an exact coherent decomposition of the
coefficient matrix of `X_(n+1)`. -/
theorem pulledSourceSectorBlock_sum (psi : AddChar F ℂ) (n : ℕ) :
    ∑ j ∈ Finset.range (n + 1), ∑ l ∈ Finset.range (n + 2),
      pulledSourceSectorBlock F psi n j l =
        rectCoeff F (rectangularCore F psi (succPNat n)) := by
  classical
  ext x y
  simp only [Matrix.sum_apply]
  let p := coreSourcePairEquiv F n (x, y)
  change (∑ j ∈ Finset.range (n + 1), ∑ l ∈ Finset.range (n + 2),
    if packetBCount F (fun i => p.1.2 i.succ) = j ∧
        packetACount F p.1.1 = l then
      rectCoeff F (rectangularCore F psi (succPNat n)) x y else 0) = _
  rw [Finset.sum_eq_single (packetBCount F (fun i => p.1.2 i.succ))]
  · rw [Finset.sum_eq_single (packetACount F p.1.1)]
    · simp
    · intro l hl hne
      simp [hne.symm]
    · intro hout
      exact (hout (Finset.mem_range.mpr
        (Nat.lt_succ_iff.mpr (packetACount_le F p.1.1)))).elim
  · intro j hj hne
    simp [hne.symm]
  · intro hout
    exact (hout (Finset.mem_range.mpr
      (Nat.lt_succ_iff.mpr (packetBCount_le F (fun i => p.1.2 i.succ))))).elim

/-- Squared magnitudes in a pulled-back block are precisely the indicators of
the corresponding source support sector. -/
theorem normSq_pulledSourceSectorBlock (psi : AddChar F ℂ)
    (n j l : ℕ)
    (x y : PacketBasis F (n + 1) × PacketBasis F (n + 1)) :
    ‖pulledSourceSectorBlock F psi n j l x y‖ ^ 2 =
      let p := coreSourcePairEquiv F n (x, y)
      if SourceSectorPredicate F n j l p then 1 else 0 := by
  unfold pulledSourceSectorBlock
  dsimp only
  by_cases hc : packetBCount F
      (fun i => (coreSourcePairEquiv F n (x, y)).1.2 i.succ) = j ∧
      packetACount F (coreSourcePairEquiv F n (x, y)).1.1 = l
  · by_cases hs : rectangularSource F (succPNat n)
        (coreSourcePairEquiv F n (x, y)).1
        (coreSourcePairEquiv F n (x, y)).2 ≠ 0
    · rw [if_pos hc, if_pos (show SourceSectorPredicate F n j l
          (coreSourcePairEquiv F n (x, y)) from ⟨hs, hc⟩),
        norm_rectCoeff_rectangularCore_apply,
        normSq_rectangularSource, if_pos hs]
    · rw [if_pos hc, if_neg (show ¬ SourceSectorPredicate F n j l
          (coreSourcePairEquiv F n (x, y)) from fun h => hs h.1),
        norm_rectCoeff_rectangularCore_apply,
        normSq_rectangularSource, if_neg hs]
  · rw [if_neg hc, norm_zero, zero_pow (by decide : 2 ≠ 0), if_neg]
    intro h
    exact hc h.2

/-- A finite real-valued indicator sum is the cardinality of its subtype. -/
theorem sum_indicator_eq_card {alpha : Type*} [Fintype alpha]
    (P : alpha → Prop) [DecidablePred P] :
    (∑ x, if P x then (1 : ℝ) else 0) = Fintype.card {x // P x} := by
  rw [Fintype.card_subtype]
  simp

set_option maxHeartbeats 400000 in
/-- Reindex the norm sum from coefficient indices to source indices. Kept as a
separate lemma to prevent the large finite function types from obscuring the
subsequent cardinality calculation. -/
theorem sum_normSq_pulledSourceSectorBlock (psi : AddChar F ℂ)
    (n j l : ℕ) :
    (∑ z : CoeffIndexPair F n,
      ‖pulledSourceSectorBlock F psi n j l z.1 z.2‖ ^ 2) =
      ∑ p : SourceIndexPair F n,
        if SourceSectorPredicate F n j l p then (1 : ℝ) else 0 := by
  apply Fintype.sum_equiv (coreSourcePairEquiv F n)
  intro z
  exact normSq_pulledSourceSectorBlock F psi n j l z.1 z.2

set_option maxHeartbeats 400000 in
/-- The squared norm of a concrete pulled-back sector is its exact number of
source entries. -/
theorem schmidtNormSq_pulledSourceSectorBlock (psi : AddChar F ℂ)
    (n j l : ℕ) :
    schmidtNormSq (pulledSourceSectorBlock F psi n j l) =
      (((n + 1).choose l * (Fintype.card F) ^ (n + 1)) *
        (n.choose j * (Fintype.card F) ^ n) : ℕ) := by
  classical
  unfold schmidtNormSq
  rw [← Fintype.sum_prod_type']
  rw [sum_normSq_pulledSourceSectorBlock, sum_indicator_eq_card]
  have hcard := card_sourceSectorPredicate F n j l
  exact_mod_cast hcard

/-- Total number of nonzero source entries. -/
theorem card_rectangularSource_support (n : ℕ) :
    Fintype.card {p : SourceIndexPair F n //
      rectangularSource F (succPNat n) p.1 p.2 ≠ 0} =
      (2 * Fintype.card F) ^ (n + 1) * (2 * Fintype.card F) ^ n := by
  calc
    Fintype.card {p : SourceIndexPair F n //
        rectangularSource F (succPNat n) p.1 p.2 ≠ 0} =
        Fintype.card (SourceParameters F n) :=
      Fintype.card_congr (sourceSupportEquiv F n).symm
    _ = _ := by
      simp [SourceParameters, PacketBasis, Vq, Fintype.card_prod,
        Fintype.card_sum]
      ring

set_option maxHeartbeats 400000 in
/-- Reindex the total coefficient norm to the support indicator of the source. -/
theorem sum_normSq_rectCoeff_rectangularCore (psi : AddChar F ℂ) (n : ℕ) :
    (∑ z : CoeffIndexPair F n,
      ‖rectCoeff F (rectangularCore F psi (succPNat n)) z.1 z.2‖ ^ 2) =
      ∑ p : SourceIndexPair F n,
        if rectangularSource F (succPNat n) p.1 p.2 ≠ 0 then (1 : ℝ) else 0 := by
  apply Fintype.sum_equiv (coreSourcePairEquiv F n)
  intro z
  rw [norm_rectCoeff_rectangularCore_apply, normSq_rectangularSource]

set_option maxHeartbeats 400000 in
/-- Exact squared Hilbert--Schmidt norm of the coefficient matrix of `X_(n+1)`. -/
theorem schmidtNormSq_rectCoeff_rectangularCore_exact
    (psi : AddChar F ℂ) (n : ℕ) :
    schmidtNormSq (rectCoeff F (rectangularCore F psi (succPNat n))) =
      ((2 * Fintype.card F) ^ (n + 1) * (2 * Fintype.card F) ^ n : ℕ) := by
  classical
  unfold schmidtNormSq
  rw [← Fintype.sum_prod_type']
  change (∑ z : CoeffIndexPair F n,
    ‖rectCoeff F (rectangularCore F psi (succPNat n)) z.1 z.2‖ ^ 2) = _
  rw [sum_normSq_rectCoeff_rectangularCore, sum_indicator_eq_card]
  have hcard := card_rectangularSource_support F n
  exact_mod_cast hcard

/-- Normalized weight of a pulled-back source sector. -/
noncomputable def pulledSourceSectorWeight (psi : AddChar F ℂ)
    (n j l : ℕ) : ℝ :=
  schmidtNormSq (pulledSourceSectorBlock F psi n j l) /
    schmidtNormSq (rectCoeff F (rectangularCore F psi (succPNat n)))

/-- The weight computed directly from `X_(n+1)` is the exact binomial weight
of Eq. (5.17), with `j=k-1`. -/
theorem pulledSourceSectorWeight_eq (psi : AddChar F ℂ)
    (n j l : ℕ) :
    pulledSourceSectorWeight F psi n j l =
      ((n.choose j : ℝ) * ((n + 1).choose l : ℝ)) / 2 ^ (2 * n + 1) := by
  rw [pulledSourceSectorWeight,
    schmidtNormSq_pulledSourceSectorBlock,
    schmidtNormSq_rectCoeff_rectangularCore_exact]
  push_cast
  let q : ℝ := Fintype.card F
  have hq : q ≠ 0 := by
    have : 0 < Fintype.card F := Fintype.card_pos
    dsimp [q]
    exact_mod_cast this.ne'
  have hexp : n + 1 + n = 2 * n + 1 := by omega
  have hqpow : q ^ (n + 1) * q ^ n = q ^ (2 * n + 1) := by
    rw [← pow_add, hexp]
  have h2pow : (2 : ℝ) ^ (n + 1) * 2 ^ n = 2 ^ (2 * n + 1) := by
    rw [← pow_add, hexp]
  change
    ((((n + 1).choose l : ℝ) * q ^ (n + 1)) *
        ((n.choose j : ℝ) * q ^ n)) /
      ((2 * q) ^ (n + 1) * (2 * q) ^ n) = _
  rw [mul_pow, mul_pow]
  field_simp [hq, hqpow, h2pow]
  ring

/-- The same result, literally in terms of the manuscript's `sectorWeight`. -/
theorem pulledSourceSectorWeight_eq_sectorWeight (psi : AddChar F ℂ)
    (n j l : ℕ) :
    pulledSourceSectorWeight F psi n j l = sectorWeight (n + 1) j l := by
  rw [pulledSourceSectorWeight_eq]
  unfold sectorWeight
  congr 1

/-- The concrete source-sector weights computed from `X_(n+1)` sum to one. -/
theorem pulledSourceSectorWeight_sum (psi : AddChar F ℂ) (n : ℕ) :
    ∑ j ∈ Finset.range (n + 1), ∑ l ∈ Finset.range (n + 2),
      pulledSourceSectorWeight F psi n j l = 1 := by
  simp_rw [pulledSourceSectorWeight_eq_sectorWeight]
  exact sectorWeight_sum (n + 1) (by omega)

/-! ## Identification with the literal output count blocks -/

omit [Field F] [Fintype F] [DecidableEq F] in
theorem isFoldedB_iff_colours (z : FoldedSite F) :
    IsFoldedB F z ↔
      siteColour F z.1 = .B ∧ siteColour F z.2 = .B := by
  rcases z with ⟨a, b⟩
  cases a <;> cases b <;> simp [IsFoldedB, siteColour]

omit [Field F] [Fintype F] [DecidableEq F] in
theorem isFoldedA_iff_colours (z : FoldedSite F) :
    IsFoldedA F z ↔
      siteColour F z.1 = .A ∧ siteColour F z.2 = .A := by
  rcases z with ⟨a, b⟩
  cases a <;> cases b <;> simp [IsFoldedA, siteColour]

omit [Fintype F] in
/-- On source support, the two right packets have the same visible colour at
every site, including the marked `|1_B><0_B|` site. -/
theorem source_right_colours_eq (n : ℕ) (u v : RectBasis F (n + 1))
    (hs : rectangularSource F (succPNat n) u v ≠ 0) (i : Fin (n + 1)) :
    siteColour F (u.2 i) = siteColour F (v.2 i) := by
  have h := (rectangularSource_ne_zero_iff F (succPNat n) u v).mp hs
  cases i using Fin.cases with
  | zero => simp [h.2.2.1, h.2.2.2, siteColour]
  | succ i => rw [h.2.1 i.succ (by simp)]

omit [Fintype F] in
/-- The marked `B` site contributes one in addition to the right tail count. -/
theorem packetBCount_source_right (n : ℕ) (u v : RectBasis F (n + 1))
    (hs : rectangularSource F (succPNat n) u v ≠ 0) :
    packetBCount F u.2 = packetBCount F (fun i => u.2 i.succ) + 1 := by
  have h := (rectangularSource_ne_zero_iff F (succPNat n) u v).mp hs
  unfold packetBCount
  rw [Fin.card_filter_univ_succ]
  simp [h.2.2.1, siteColour]

omit [Fintype F] in
/-- On a nonzero coefficient entry, its folded left `B` count is the full
right-source `B` count. -/
theorem foldedBCount_eq_sourceRight (n : ℕ)
    (x y : PacketBasis F (n + 1) × PacketBasis F (n + 1))
    (hs : rectangularSource F (succPNat n) (coreSourcePairEquiv F n (x, y)).1
      (coreSourcePairEquiv F n (x, y)).2 ≠ 0) :
    foldedBCount F (foldPacketEquiv F (n + 1) x) =
      packetBCount F (coreSourcePairEquiv F n (x, y)).1.2 := by
  let p := coreSourcePairEquiv F n (x, y)
  have hp1 : p.1 = rectangularCircuitPerm F (n + 1) (x.1, y.1) := by rfl
  have hp2 : p.2 = rectangularCircuitPerm F (n + 1) (x.2, y.2) := by rfl
  unfold foldedBCount packetBCount
  apply congrArg Finset.card
  ext i
  simp only [Finset.mem_filter, Finset.mem_univ, true_and]
  rw [isFoldedB_iff_colours]
  have hx1 := siteColour_rectangularCircuitPerm_snd F (n + 1) (x.1, y.1) i
  have hx2 := siteColour_rectangularCircuitPerm_snd F (n + 1) (x.2, y.2) i
  have heq := source_right_colours_eq F n p.1 p.2 hs i
  have heq' :
      siteColour F ((rectangularCircuitPerm F (n + 1) (x.1, y.1)).2 i) =
        siteColour F ((rectangularCircuitPerm F (n + 1) (x.2, y.2)).2 i) := by
    simpa [hp1, hp2] using heq
  change (siteColour F (x.1 i) = .B ∧ siteColour F (x.2 i) = .B) ↔
    siteColour F (p.1.2 i) = .B
  rw [hp1]
  constructor
  · rintro ⟨h1, h2⟩
    rw [hx1]
    exact h1
  · intro hp
    constructor
    · rwa [← hx1]
    · rw [← hx2, ← heq']
      exact hp

omit [Fintype F] in
/-- On a nonzero coefficient entry, its folded right `A` count is the
left-source `A` count. -/
theorem foldedACount_eq_sourceLeft (n : ℕ)
    (x y : PacketBasis F (n + 1) × PacketBasis F (n + 1))
    (hs : rectangularSource F (succPNat n) (coreSourcePairEquiv F n (x, y)).1
      (coreSourcePairEquiv F n (x, y)).2 ≠ 0) :
    foldedACount F (foldPacketEquiv F (n + 1) y) =
      packetACount F (coreSourcePairEquiv F n (x, y)).1.1 := by
  let p := coreSourcePairEquiv F n (x, y)
  have hp1 : p.1 = rectangularCircuitPerm F (n + 1) (x.1, y.1) := by rfl
  have hp2 : p.2 = rectangularCircuitPerm F (n + 1) (x.2, y.2) := by rfl
  have hsource := (rectangularSource_ne_zero_iff F (succPNat n) p.1 p.2).mp hs
  have hleft :
      (rectangularCircuitPerm F (n + 1) (x.1, y.1)).1 =
        (rectangularCircuitPerm F (n + 1) (x.2, y.2)).1 := by
    simpa [hp1, hp2] using hsource.1
  unfold foldedACount packetACount
  apply congrArg Finset.card
  ext i
  simp only [Finset.mem_filter, Finset.mem_univ, true_and]
  rw [isFoldedA_iff_colours]
  have hy1 := siteColour_rectangularCircuitPerm_fst F (n + 1) (x.1, y.1) i
  have hy2 := siteColour_rectangularCircuitPerm_fst F (n + 1) (x.2, y.2) i
  change (siteColour F (y.1 i) = .A ∧ siteColour F (y.2 i) = .A) ↔
    siteColour F (p.1.1 i) = .A
  rw [hp1]
  constructor
  · rintro ⟨h1, h2⟩
    rw [hy1]
    exact h1
  · intro hp
    constructor
    · rwa [← hy1]
    · rw [← hy2, ← hleft]
      exact hp

/-- Nonzero coefficient entries are exactly the pullback of source support. -/
theorem rectCoeff_rectangularCore_ne_zero_iff_source (psi : AddChar F ℂ) (n : ℕ)
    (x y : PacketBasis F (n + 1) × PacketBasis F (n + 1)) :
    rectCoeff F (rectangularCore F psi (succPNat n)) x y ≠ 0 ↔
      rectangularSource F (succPNat n) (coreSourcePairEquiv F n (x, y)).1
        (coreSourcePairEquiv F n (x, y)).2 ≠ 0 := by
  rw [← norm_ne_zero_iff, norm_rectCoeff_rectangularCore_apply,
    norm_ne_zero_iff]

/-- Put the pulled-back source block into the folded onsite basis. -/
noncomputable def foldedPulledSourceSectorBlock (psi : AddChar F ℂ)
    (n j l : ℕ) : Matrix (FoldedPacket F (n + 1)) (FoldedPacket F (n + 1)) ℂ :=
  Matrix.reindex (foldPacketEquiv F (n + 1)) (foldPacketEquiv F (n + 1))
    (pulledSourceSectorBlock F psi n j l)

/-- The pulled-back source block is exactly the manuscript's literal output
count block `(k,l)=(j+1,l)`. This is where the block-transpose colour theorem
is used. -/
theorem foldedPulledSourceSectorBlock_eq_countBlock (psi : AddChar F ℂ)
    (n j l : ℕ) :
    foldedPulledSourceSectorBlock F psi n j l =
      rectangularCountBlock F psi (succPNat n) (j + 1) l := by
  classical
  ext a b
  let x := (foldPacketEquiv F (n + 1)).symm a
  let y := (foldPacketEquiv F (n + 1)).symm b
  let M := rectCoeff F (rectangularCore F psi (succPNat n))
  have hfoldx : foldPacketEquiv F (n + 1) x = a :=
    (foldPacketEquiv F (n + 1)).apply_symm_apply a
  have hfoldy : foldPacketEquiv F (n + 1) y = b :=
    (foldPacketEquiv F (n + 1)).apply_symm_apply b
  change (if packetBCount F
      (fun i => (coreSourcePairEquiv F n (x, y)).1.2 i.succ) = j ∧
        packetACount F (coreSourcePairEquiv F n (x, y)).1.1 = l then M x y else 0) =
    if foldedBCount F a = j + 1 ∧ foldedACount F b = l then M x y else 0
  by_cases hM : M x y ≠ 0
  · have hs := (rectCoeff_rectangularCore_ne_zero_iff_source F psi n x y).mp hM
    have hBfull := foldedBCount_eq_sourceRight F n x y hs
    have hBtail := packetBCount_source_right F n
      (coreSourcePairEquiv F n (x, y)).1 (coreSourcePairEquiv F n (x, y)).2 hs
    have hA := foldedACount_eq_sourceLeft F n x y hs
    have hpred :
        (packetBCount F
            (fun i => (coreSourcePairEquiv F n (x, y)).1.2 i.succ) = j ∧
          packetACount F (coreSourcePairEquiv F n (x, y)).1.1 = l) ↔
        (foldedBCount F a = j + 1 ∧ foldedACount F b = l) := by
      rw [← hfoldx, ← hfoldy, hBfull, hBtail, hA]
      omega
    by_cases hp : packetBCount F
        (fun i => (coreSourcePairEquiv F n (x, y)).1.2 i.succ) = j ∧
        packetACount F (coreSourcePairEquiv F n (x, y)).1.1 = l
    · rw [if_pos hp, if_pos (hpred.mp hp)]
    · rw [if_neg hp, if_neg (fun h => hp (hpred.mpr h))]
  · push_neg at hM
    simp [hM]

/-- Reindexing both axes by equivalences preserves the squared
Hilbert--Schmidt norm. -/
theorem schmidtNormSq_reindex_equiv
    {m n m' n' : Type*} [Fintype m] [Fintype n] [Fintype m'] [Fintype n']
    (e : m ≃ m') (f : n ≃ n') (M : Matrix m n ℂ) :
    schmidtNormSq (Matrix.reindex e f M) = schmidtNormSq M := by
  classical
  simp only [schmidtNormSq, Matrix.reindex_apply, Matrix.submatrix]
  calc
    (∑ i : m', ∑ j : n', ‖M (e.symm i) (f.symm j)‖ ^ 2) =
        ∑ i : m', ∑ j : n, ‖M (e.symm i) j‖ ^ 2 := by
      apply Finset.sum_congr rfl
      intro i hi
      exact Equiv.sum_comp f.symm (fun j => ‖M (e.symm i) j‖ ^ 2)
    _ = ∑ i : m, ∑ j : n, ‖M i j‖ ^ 2 :=
      Equiv.sum_comp e.symm (fun i => ∑ j : n, ‖M i j‖ ^ 2)

/-- Thus folding a pulled-back source block does not change its norm. -/
theorem schmidtNormSq_foldedPulledSourceSectorBlock (psi : AddChar F ℂ)
    (n j l : ℕ) :
    schmidtNormSq (foldedPulledSourceSectorBlock F psi n j l) =
      schmidtNormSq (pulledSourceSectorBlock F psi n j l) :=
  schmidtNormSq_reindex_equiv _ _ _

/-- Folding the complete coefficient matrix does not change its norm. -/
theorem schmidtNormSq_foldedRectCoeff (psi : AddChar F ℂ) (n : ℕ) :
    schmidtNormSq (foldedRectCoeff F (rectangularCore F psi (succPNat n))) =
      schmidtNormSq (rectCoeff F (rectangularCore F psi (succPNat n))) :=
  schmidtNormSq_reindex_equiv _ _ _

/-- Consequently the literal output count weight agrees with the pulled-back
source weight. -/
theorem rectangularCountWeight_eq_pulledSourceSectorWeight
    (psi : AddChar F ℂ) (n j l : ℕ) :
    rectangularCountWeight F psi (succPNat n) (j + 1) l =
      pulledSourceSectorWeight F psi n j l := by
  unfold rectangularCountWeight pulledSourceSectorWeight
  rw [← foldedPulledSourceSectorBlock_eq_countBlock,
    schmidtNormSq_foldedPulledSourceSectorBlock,
    schmidtNormSq_foldedRectCoeff]

/-- Exact unnormalized squared norm of the literal `(j+1,l)` count block. -/
theorem schmidtNormSq_rectangularCountBlock_exact
    (psi : AddChar F ℂ) (n j l : ℕ) :
    schmidtNormSq (rectangularCountBlock F psi (succPNat n) (j + 1) l) =
      (((n + 1).choose l * (Fintype.card F) ^ (n + 1)) *
        (n.choose j * (Fintype.card F) ^ n) : ℕ) := by
  rw [← foldedPulledSourceSectorBlock_eq_countBlock,
    schmidtNormSq_foldedPulledSourceSectorBlock,
    schmidtNormSq_pulledSourceSectorBlock]

/-- **Eq. (5.17) for the actual count blocks of `X_t`.** -/
theorem rectangularCountWeight_eq_sectorWeight
    (psi : AddChar F ℂ) (n j l : ℕ) :
    rectangularCountWeight F psi (succPNat n) (j + 1) l =
      sectorWeight (n + 1) j l := by
  rw [rectangularCountWeight_eq_pulledSourceSectorWeight,
    pulledSourceSectorWeight_eq_sectorWeight]

end SqrtOpEnt
